---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: beets
  annotations:
    nfs.io/storage-path: "data01/beets"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: musics
  annotations:
    nfs.io/storage-path: "data02/media/musics"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads
  annotations:
    nfs.io/storage-path: "data02/downloads/musics"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
