kind: Deployment
apiVersion: apps/v1
metadata:
  name: beets
  labels:
    app: beets
    part-of: beets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beets
      part-of: beets
  template:
    metadata:
      labels:
        app: beets
        part-of: beets
    spec:
      containers:
      - name: beets
        image: ghcr.io/linuxserver/beets:1.4.9-ls94
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Paris"
        - name: UMASK
          value: "022"
        volumeMounts:
        - name: beets
          mountPath: /config
        - name: musics
          mountPath: /music
        - name: downloads
          mountPath: /downloads/musics
      volumes:
      - name: beets
        persistentVolumeClaim:
          claimName: beets
      - name: musics
        persistentVolumeClaim:
          claimName: musics
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
