apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: beets
spec:
  provider: vault
  secretObjects:
  - secretName: beets
    type: Opaque
    data: 
    - objectName: JELLYFIN_TOKEN
      key: JELLYFIN_TOKEN
  parameters:
    vaultAddress: 'http://vault.vault:8200'
    vaultKubernetesMountPath: 'k8s-vault-csi'
    roleName: beets
    objects: |
      - objectName: "JELLYFIN_TOKEN"
        secretPath: "apps-kv/data/beets/config"
        secretKey: "JELLYFIN_TOKEN"
